repos:
    - repo: local
      hooks:
          - id: ruff-format
            name: Format with Ruff
            entry: poetry run ruff format
            language: system
            types: [python]
            pass_filenames: false
            args: ["aiobybit"]

          - id: ruff-lint
            name: Check with Ruff
            entry: poetry run ruff check
            language: system
            types: [python]
            pass_filenames: false
            always_run: true
            args: ["aiobybit", "--fix"]

          - id: mypy
            name: Validate types with MyPy
            entry: poetry run mypy
            language: system
            types: [python]
            pass_filenames: false
            args:
                - "aiobybit"
